#!/bin/bash

##
#   Copyright 2017 @packetpilot <point.it@howiget.email>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#!/bin/bash

# Variables
URLBASE=https://github.com/prometheus/prometheus/releases
VERS=$(curl -s "${URLBASE}"/latest 2>&1 \
  | cut -d '/' -f8 | cut -d '"' -f1 | cut -c 2-)
EXTURL="${URLBASE}"/download/v"${VERS}"/prometheus-"${VERS}".darwin-amd64.tar.gz
TMPDIR=/tmp/prometheus
TARLOC=${TMPDIR}/prometheus.tar.gz
TARGET=${3}/usr/local/share/prometheus
TARGEXECS=${3}/usr/local/bin

mkdir -p "${TMPDIR}"

curl -Lso \
  "${TARLOC}" "${EXTURL}"

if [ -d "${TARGET}" ]; then
  mv "${TARGET}" "${TARGET}.$(date +%s)"
fi

mkdir -p "${TARGET}"

tar xzf "${TARLOC}" -C "${TARGET}" --strip 1

for i in $(find "${TARGET}" -maxdepth 1 -perm -111 -type f | rev \
  | cut -d '/' -f 1 | rev); do
  ln -sf "${TARGET}/${i}" "${TARGEXECS}/${i}"
done

chown -R root:admin "${TARGET}"
chmod -R g+w "${TARGET}"

rm -rf "${TMPDIR}"
