#!/bin/bash

##
#   Copyright 2017 @packetpilot <point.it@howiget.email>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Variables
EXTURL=https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
TMPDIR=/tmp/chrome
DMGLOC=${TMPDIR}/googlechrome.dmg

mkdir -p "${TMPDIR}"

curl -Lso "${DMGLOC}" "${EXTURL}"

hdiutil attach -nobrowse "${DMGLOC}"

cp -R /Volumes/Google\ Chrome/Google\ Chrome.app "${3}/Applications"

hdiutil unmount /Volumes/Google\ Chrome

rm -rf "${TMPDIR}"
