#!/bin/bash

##
#   Copyright 2017 @packetpilot <point.it@howiget.email>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Variables
EXTURL=https://dl.google.com/chrome-remote-desktop/chromeremotedesktop.dmg
TMPDIR=/tmp/chromote
DMGLOC=${TMPDIR}/chromeremotedesktop.dmg
VOLNAME=/Volumes/Chrome\ Remote\ Desktop\ Host*

mkdir -p "${TMPDIR}"

curl -Lso "${DMGLOC}" "${EXTURL}"

hdiutil attach -nobrowse "${DMGLOC}"

VOLNAME=/Volumes/$(grep "Chrome Remote Desktop" <(ls /Volumes))

installer -pkg "${VOLNAME}/Chrome Remote Desktop Host.pkg" -target "${3}"

hdiutil unmount "${VOLNAME}"

rm -rf "${TMPDIR}"
