#!/bin/bash

##
#   Copyright 2017 @packetpilot <point.it@howiget.email>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# NOTE: there are more secure ways to distribute the CA file. Its existence in
# this script is intended only to keep the package payload-free without relying
# on potentially-confusing `curl` action. Of course, YMMV; consider what makes
# sense to your org and your security needs.

# Set variables
CADIR=${3}/var/root/CA
CAFILE=${CADIR}/llett.io-ca.crt
TRUST=trustAsRoot # trustAsRoot: if root cert's unkown; else trustRoot (safer)
DIRPERSISTENCE=no # 'no' == no, anyhting else == yes
FILEPERSISTENCE=no # 'no' == no, anyhting else == yes
RANDFILLPASSES=3 # only used in cases where FILEPERSISTENCE=no

mkdir -p "${CADIR}"

cat > "${CAFILE}" <<EOF
-----BEGIN CERTIFICATE-----
MIIGEzCCA/ugAwIBAgICEAEwDQYJKoZIhvcNAQELBQAwgZ8xCzAJBgNVBAYTAlVT
MRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1Nb3VudGFpbiBWaWV3MREw
DwYDVQQKDAhsbGV0dC5pbzEPMA0GA1UECwwGRGlnT3BzMRgwFgYDVQQDDA9sZXR0
LmlvIHJvb3QgQ0ExJTAjBgkqhkiG9w0BCQEWFnBvaW50Lml0QGhvd2lnZXQuZW1h
aWwwHhcNMTcwOTIxMDU1NzAyWhcNMjcwOTE5MDU1NzAyWjCBkDELMAkGA1UEBhMC
VVMxEzARBgNVBAgMCkNhbGlmb3JuaWExETAPBgNVBAoMCGxsZXR0LmlvMQ8wDQYD
VQQLDAZEaWdPcHMxITAfBgNVBAMMGGxsZXR0LmlvIEludGVybWVkaWF0ZSBDQTEl
MCMGCSqGSIb3DQEJARYWcG9pbnQuaXRAaG93aWdldC5lbWFpbDCCAiIwDQYJKoZI
hvcNAQEBBQADggIPADCCAgoCggIBAOpK6laqde8ZmePR4sGZZVmPqy4A78FTh0Xe
FxqlA1uSgtk8vOY4SvwFBqUfXjoQBRxx+AANtnWkM8TZLO97krrWnItHdyH9hYBl
leTjlofNx7hMhrXt4FF1NKAaLJnsuscEVuFK/Ltw8fV7Zr4HLrbqlwZbOiDY4boz
7GcYowUPtTJ4Xs3tFhckscqnsr3id9fwit28dYOUapHcI7UbFjsTRFmoEr902JnL
CgJaVod0/QbYtOBrcuY55lkBjt0ZEoAV5UQV1D3PWw5Jeu0xKncmNbC2pb55Mih7
zFwDhnIk1iHSUrerw4ZPV1Wzz+x4NV+SQqx3RF7poNC9ASrdvmDtM41rZgDcz3hR
FFCuz+mw8tGTq7NoqPPDQ3TKnvfnFG74k4wmTgZWVaRVYkuqux/RaDfGSdP9ykRT
/0aN7s1AekQxDOoobQVbEpwwO53ydeBL8zXOoRZRptP2QOg+ztpJXnC88BRCfnRi
v/x3ia9A6Aaqk2qzWaqii+1DjHbL4jEltEKWA0k9dN004gJk6B9tMWZUbVVKSQy8
3oXAH9jwpiUGzZGpnqykT+5FplD5EQGdmhzR5cWbjwnwnddwJUN7tWw09RKorEmH
yj3QfF5l1gTxmEL8X9NrGkBFujons4aXPbGh6g0gcHZT3NLqx57bU8r5JMp0AYPE
y5pKs6q/AgMBAAGjZjBkMB0GA1UdDgQWBBRTHjEBauqAboJj4xRfKJtkmaOWETAf
BgNVHSMEGDAWgBSyTgkN/OanWsV90TD2/B6+xWJF7DASBgNVHRMBAf8ECDAGAQH/
AgEAMA4GA1UdDwEB/wQEAwIBhjANBgkqhkiG9w0BAQsFAAOCAgEAAHhKg5DTUOy+
3sIRS/wyvRWpzNXsZaldCThZkhyCwEqfI2x0oFly5/Fk/yN2Vkk70MTNxpXZND10
FjISGJjJ82PJp1sU24e1oH8XC6rOjUR0JgI53eVk0+SYbFsQL4EAc4WmLbB3VWDO
s0JqglncYyodZECPl0JODvGYLkiyxNANiDdYpLiC5bICunYX6BYuLsHhdR8y6D6Y
kzc2iuXrpum/HB6xV0c6kIzLr9TXS9i5hlwBe6SkDKn4LTHsZX5d7/i0X2x+cxx0
MoigcyoE8AiPbSACOzXWvyc4TJ4CBGehkVK3+E4kGaY9PbdjQfYsRe9WlTqX5sPc
NvXu57Sn0XOVXlJLgIufLvdxRzjmkwNBlJXhGqP5c23iYaxWdtUZurA8iaGKNMpo
CSutSLMq9q+scWezaQbN841HBXY5aok2pcD4gv3PL9k34F3dVDMJSv3YXuc9lii1
2B0gEEM3Hen+iwbkqOB8u4DCTCKNICGQhefEk7ltYjxw1ZF5uwAkL3gxeTnpvN3y
RYbhwj+Lahf8RKIa2BAx2IVFDi6ExD773bISoT0ab4kSSq9O5uax6z3AzyzEUfd8
jOg7Q4ZjP469vsk+TfjgHR0frlpZ7s3Q3fXUFC5r4DIz9Le2UsRzobw4mBZVJvYT
+qHdZYgr9rWORBPckGfcHgBT4fTuyfU=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIGJjCCBA6gAwIBAgIJAMlMXZrTq7TgMA0GCSqGSIb3DQEBCwUAMIGfMQswCQYD
VQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNTW91bnRhaW4g
VmlldzERMA8GA1UECgwIbGxldHQuaW8xDzANBgNVBAsMBkRpZ09wczEYMBYGA1UE
AwwPbGV0dC5pbyByb290IENBMSUwIwYJKoZIhvcNAQkBFhZwb2ludC5pdEBob3dp
Z2V0LmVtYWlsMB4XDTE3MDkyMTA1MzEwMloXDTM3MDkxNjA1MzEwMlowgZ8xCzAJ
BgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1Nb3VudGFp
biBWaWV3MREwDwYDVQQKDAhsbGV0dC5pbzEPMA0GA1UECwwGRGlnT3BzMRgwFgYD
VQQDDA9sZXR0LmlvIHJvb3QgQ0ExJTAjBgkqhkiG9w0BCQEWFnBvaW50Lml0QGhv
d2lnZXQuZW1haWwwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDweKSA
4oauXrGmSaZa7czJXKH1+W6tySzYF7aWJs6lMk+EgvXKIpv51YcP01I7dnpzhisH
MaC1g0PExvH7N+ShTOIEP/r+9gwSOy5fv3VQGyFKtx0Th1twDcstLK5PzVN5tLB8
qyZhA6ZCP9X98hGYeQu9MKXy1JWXVcyKMOWjNLsNSrcVvM8nzrpbgO6UgE9zmz+j
DZY39EMIweg9odLwo4ZnRskh6PPB9+kHmzq9HiG7VPtzf/i24AYfNogtp06sLM8A
91XfpQa/jTITlczoNIaFsXBI4l1o82XogVW43nX3Zqs4wQT3p6RC5LaWNdA7oW/I
pQWtNz8L75yjdS1Fwni+fmtrFDZsCOwSLt1KuBQgTIC+2EtZl1svoIWvtZn4zR+Q
JotW4lxwCdI6y7A6xt2itp3LPwc6WjyQqIXdKGPrR/pBDP7iFN5V07xfc1hcTls8
o3mafk9/ThGVR0qYmsYaz0kXngbj8t6oP/qlF7ygSd54Ofdu43pOcFJKM1U2+RJG
G0LvK1ErdcmVIzU6NbImtow50CdJjeuRq/eBfroprsel17iXAKQxN6ll4U9/g4Y8
GD/S26G3F13j+utiKfu3RrebacvJh3zcwQLlWFUMUsu8fc3pbCbsEcJRYsByrbqV
yCc4i1GuzP0rGXFTteoKm0fwtQWQLR0S6G6k9QIDAQABo2MwYTAdBgNVHQ4EFgQU
sk4JDfzmp1rFfdEw9vwevsViRewwHwYDVR0jBBgwFoAUsk4JDfzmp1rFfdEw9vwe
vsViRewwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAYYwDQYJKoZIhvcN
AQELBQADggIBAJwI6WY1FBfUGCrGmsLza4MLgPcYoyZBKh7NY31+GKlUawNspPuO
PeAZ7ix0TH8YbhKZTz4Ec/YYE2iddxHY7/ZvJ4xWeumaNUaHnGX08bjDyiGTbP8Y
5yau3aCzc8C2dORCYSMfNrdZiKQWs97jiW7Noa+Ab4xawAHcNvcOYG7RcFpnpNtF
E5KWL24rpqS2U22kFT/NxkVMi25tZW2SeNo5jhF11A3OYLZIFnitc2n1POVkEePu
P8rkQJs3yM3Ef6LLxr1f8Lo4FbZAe2qcVKZo1YLpkFTK19c1FqY46zkjKVBvGBS1
/jbPd3/Lpv2GqW0XiTnqxh2iT38CZye0w4GvO5K5CVjlyzqj6AX15iHj1FioN5kh
S+7mRAr4eKc0wDfWUp39Mq0BxSiy/0ICRjMVVFZkz5yUlheeoMa0amsj5ygSI+Ir
AGKSVQorVNEOVWR1QxkhrVdl6yTWHA/+IQ9rQeak/UJw0U1CKlImjWXiaE/aJjam
Sv0e0cy/h21URzZ/Ar+OXHlZJCwQ4nckLOTjY4zqWL0GZ8Dr05Xqcpuw45Om75NO
HTUng5tEnqOpaqxDfCOgUCXllr6ffx7eHRW1RZzvy4Tny5C9Y5E7QdWEOZOP7Wg7
I3QpcYckTKbgw66MLdTDGzdDN+ii/XYef4f+YGGvVGod1tulcwR1BPd6
-----END CERTIFICATE-----
EOF

security add-trusted-cert -d -r "${TRUST}" \
  -k "${3}/Library/Keychains/System.keychain" "${CAFILE}"

if [ "${FILEPERSISTENCE}" == "no" ]; then
  # srm is gone in 10.12+
  for i in $(seq 1 ${RANDFILLPASSES}); do
    echo "randfill pass ${i}" 2>&1 # using var to pass shellcheck
    dd if=/dev/urandom of="${CAFILE}" bs=8k count=1 2>&1
  done
  rm "${CAFILE}"
fi

if [ "${DIRPERSISTENCE}" == "no" ]; then
  rm -rf "${CADIR}" # on the off-chance it's not empty
fi
