#!/bin/bash

##
#   Copyright 2017 @packetpilot <point.it@howiget.email>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# This script doesn't _seem_ polite, but it's been tested with an old 3.0.4
# version running while 3.1.1 updates right behind it. Logs continued to tail
# just fine. So, while it might be optimal for login/logout hook, or at
# loginwindow, it also seems to non-disruptively do the job on-the-fly.

# Variables
EXTURL=https://iterm2.com/downloads/stable/latest
TMPDIR=/tmp/iterm
ZIPLOC=${TMPDIR}/iTerm.zip

mkdir -p "${TMPDIR}"

curl -Lso \
  "${ZIPLOC}" "${EXTURL}"

unzip -o "${ZIPLOC}" -d "${3}"/Applications

rm -rf "${TMPDIR}"
