#!/bin/bash

##
#   Copyright 2017 @packetpilot <point.it@howiget.email>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Variables
LATEST=$(grep "release" <(curl -L https://tunnelblick.net) \
  | awk '/release/{i++}i==2' | cut -d '/' -f 3 | cut -d '"' -f 1)
EXTURL=https://tunnelblick.net/release/"${LATEST}"
TMPDIR=${3}/tmp/tunnelblick
DMGLOC=${TMPDIR}/tunnelblick.dmg
VOLPATH=/Volumes/Tunnelblick
SHASUM=$(grep "SHA256" <(curl -L https://tunnelblick.net/downloads.html) \
  | awk '/SHA256/{i++}i==2' | cut -d ';' -f 5 | cut -d '<' -f 1)
APPLOC=/Volumes/Tunnelblick/Tunnelblick.app

# Functions
hashfail() {
  echo "The sha hash did not match the expected value. Exiting." \
    >> /var/log/install.log
  exit 1
}

mkdir -p "${TMPDIR}"

curl -Lso "${DMGLOC}" "${EXTURL}"

if [[ $(shasum -a 256 "${DMGLOC}" | cut -d ' ' -f 1) != "${SHASUM}" ]]; then
  hashfail
fi

hdiutil attach -nobrowse "${DMGLOC}"

cp -R "${APPLOC}" "${3}/Applications"

hdiutil unmount "${VOLPATH}"

rm -rf "${TMPDIR}"
