#!/bin/bash
##
#   Copyright 2017 @packetpilot <point.it@howiget.email>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Variables
LATEST=$(curl -Ls http://download.virtualbox.org/virtualbox/LATEST-STABLE.TXT)
BASEURL=http://download.virtualbox.org/virtualbox/${LATEST}
DMGNAME=$(curl -Ls "${BASEURL}" | grep OSX | cut -d '"' -f 2)
EXTURL=${BASEURL}/${DMGNAME}
MD5SUM=$(curl -Ls "${BASEURL}"/MD5SUMS | grep "${DMGNAME}" | cut -d ' ' -f 1)
TMPDIR=/tmp/virtualbox
DMGLOC=${TMPDIR}/VirtualBox.dmg
VOLPATH=/Volumes/VirtualBox
PKGLOC=${VOLPATH}/VirtualBox.pkg

# Functions
hashfail() {
  echo "The md5 hash did not match the expected value. Exiting." \
    >> /var/log/install.log
  exit 1
}

mkdir -p "${TMPDIR}"

curl -Lso "${DMGLOC}" "${EXTURL}"

if [[ $(md5 -q "${DMGLOC}") != "${MD5SUM}" ]]; then
  hashfail
fi

hdiutil attach -nobrowse "${DMGLOC}"

installer -pkg "${PKGLOC}" -target "${3}"

hdiutil unmount "${VOLPATH}"

rm -rf "${TMPDIR}"
